-- local M = {
-- 	"jose-elias-alvarez/null-ls.nvim",
-- 	opts = function(_, _)
-- 		local status, null_ls = pcall(require, "null-ls")
-- 		if (not status) then return end
-- 		-- local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
--
-- 		null_ls.setup {
-- 			debug = false,
-- 			sources = {
-- 				null_ls.builtins.formatting.goimports_reviser,
-- 				null_ls.builtins.formatting.prettierd.with({
-- 					filetypes = { "html", "json", "js", "ts", "tsx", "css" },
-- 					only_local = "node_modules/.bin",
-- 				}),
-- 				-- null_ls.builtins.formatting.gofumpt,
-- 				null_ls.builtins.diagnostics.protolint,
-- 				null_ls.builtins.diagnostics.yamllint,
-- 				null_ls.builtins.diagnostics.golangci_lint,
-- 			},
-- 			-- on_attach = function(client, bufnr)
-- 			-- 	if client.supports_method("textDocument/formatting") then
-- 			-- 		vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
-- 			-- 		vim.api.nvim_create_autocmd("BufWritePre", {
-- 			-- 			pattern = "*.json,*.js,*.ts,*.tsx,*.css,*.html",
-- 			-- 			group = augroup,
-- 			-- 			buffer = bufnr,
-- 			-- 			callback = function()
-- 			-- 				vim.lsp.buf.format({ bufnr = bufnr, async = false })
-- 			-- 			end,
-- 			-- 		})
-- 			-- 	end
-- 			-- end
-- 		}
-- 	end,
-- }
--
-- return M
